---
title: "BDA Project"
author: "Dylan, Francesco, Pragati"
output:
  pdf_document:
    toc: yes
    toc_depth: 1
  html_document:
    toc: yes
    toc_depth: '1'
    df_print: paged
  word_document:
    toc: yes
    toc_depth: '1'
bibliography: uni.bib
---

# Intrid

Hello @recomm

We now test how sensible our models are to the choice of the priors: we compared the results of Pareto-k-diagnostics for different choices of priors and the comparison is shown in the table below. After using the **weakly informative priors** previously presented, we first tested an even more **wide** and **less informative** prior for each one of the models, then we tested a biased prior, to further investigate the influence the prior has one the models. 

Given the size of the dataset, we could expect that any prior would have little influence on the model, which would resemble instead the shape of the likelihood. This consideration is clearly reflected by the results we obtained (see the table below) for the linear and hierarchical models, while guassian model is definitely sensible to the prior choice.
 
|Priors|Model|Pareto k estimates|
|---|---|---|
|alpha ~ normal(0,1)| Linear |all k < 0.5|
|beta ~ normal(0,1)|||
|sigma ~ normal(0,100)|||
||||
|alpha ~ normal(0,100)| Linear |all k < 0.5|
|beta ~ normal(0,100)|||
|sigma ~ normal(0,100)|||
||||
|alpha ~ normal(50,10)| Linear |all k < 0.5|
|beta ~ normal(50,10)|||
|sigma ~ normal(0,100)|||
||||
|---|---|---|
||||
|mu ~ normal(0,1)| Hierarchical |98.3% k < 0.5|
|tau ~ normal(0,1)||0.7% --> 0.7 < k < 1|
|sigma ~ normal(0,100)|||
||||
|mu ~ normal(0,100)| Hierarchical |97.6% k < 0.5|
|tau ~ normal(0,100)||0.9% --> 0.7 < k < 1|
|sigma ~ normal(0,10)|||
||||
|mu ~ normal(50,10)| Hierarchical |98.2% k < 0.5|
|tau ~ normal(50,10)||1.3% --> 0.7 < k < 1|
|sigma ~ normal(0,100)|||
||||
|---|---|---|
||||
|rho ~ inv_gamma(5,5)| Gaussian |9% k < 0.5|
|alpha ~ normal(0,1)||49% --> 0.7 < k < 1|
|sigma ~ normal(0,1)||7% --> k > 1|
|eta ~ normal(0,1)|||
||||
|rho ~ inv_gamma(5,0.1)| Gaussian |0% k < 0.5|
|alpha ~ normal(0,100)||97% --> 0.7 < k < 1|
|sigma ~ normal(0,100)||3% --> k > 1|
|eta ~ normal(0,100)|||
||||
|rho ~ inv_gamma(20,5)| Gaussian |0% k < 0.5|
|alpha ~ normal(50,10)||77% --> 0.7 < k < 1|
|sigma ~ normal(50,10)||21% --> k > 1|
|eta ~ normal(50,10)|||
||||







# References 
